sigwait:sigwait.c
	gcc $^ -o $@ -g
sigprocmask:sigprocmask.c
	gcc $^ -o $@ -g
sigaction:sigaction.c
	gcc $^ -o $@ -g
signal:signal.c
	gcc $^ -o $@ -g
abort:abort.c
	gcc $^ -o $@
kill:kill.c
	gcc $^ -o $@
